apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'echo -e  "configmap-key1 $CONFIGMAPVAR \n configmap-key2 $CONFIGMAPVAR2"']
      env:
      - name: CONFIGMAPVAR
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: key1
      - name: CONFIGMAPVAR2
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: key2

