# node_config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 31325
      hostPort: 31325
  - role: worker
  - role: worker
  - role: worker
