apiVersion: v1
kind: Service
metadata:  
  name: nginx-nodeport-service
spec:
  selector:    
    app: nginx2
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31325
    protocol: TCP
